services:
  - type: web
    name: playwright-python-app
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/playwright

